My feature
Ashah15/Apple.com pull request #2
Opened 2019-07-22 17:10 UTC by Ashah15

2019-07-23 00:24 UTC, mosaaleb commented
## Under review

2019-07-23 00:49 UTC, mosaaleb requested changes
## Hi @Ashah15 :wave:

### Amazing work :clap:. Your code is organized and easy to read. The UI is perfect. You have already handled most of the requirements, still there is some work to do before moving on. See my comments below.

- [ ] Also, let's make sure that our style guidelines are ok by using [stickler](https://github.com/microverseinc/linters-config/tree/master/css). It's very easy to use, just follow the link.

Please submit a new code review once you finish these minor requirements.

#### Happy coding :computer:

2019-07-23 00:49 UTC, mosaaleb commented on index.html
> +			<li>Mac</li>
All the `<li>` items inside `nav` needs to be links.

2019-07-23 00:49 UTC, mosaaleb commented on index.html
> +			<p class="top-header-subtitle">Everyone has something to share. See how people are using iPad in their unique ways to add to the worlds story.</p>
All the text inside `top-header` section are also clickable links:
- Each link is an `<a>` tag, with a `<div>` tag inside it.
- The `<div>` tag  inside the `<a>` tag should use an image as background -- [ ] The text on the original page is actually an image

2019-07-23 00:49 UTC, mosaaleb commented on index.html
> +			<div class="col"><img src="images/promo_iphone5c.jpg" class="img-responsive" alt="iphone 5c promo"></div>
The images inside the `promo-pages` section are also clickable links.

2019-07-30 23:12 UTC, Oghenebrume50 requested changes

2019-07-30 23:12 UTC, Oghenebrume50 commented on index.html
> +			<div class="hero-section">
Hi, you are making great progress but you did not correc this point from the previous review you got, please pass the images as backgorund images usng CSS
Each link is an <a> tag, with a <div> tag inside it.
The <div> tag inside the <a> tag should use an image as background -- [ ] The text on the original page is actually an image

2019-07-30 23:12 UTC, Oghenebrume50 commented on index.html
> +		<section class="promo-pages">
Do the same for the images in this container also
Each link is an <a> tag, with a <div> tag inside it.
The <div> tag inside the <a> tag should use an image as background -- [ ] The text on the original page is actually an image

2019-08-06 21:03 UTC, Oghenebrume50 approved these changes

2019-08-06 21:03 UTC, Oghenebrume50 commented on index.html
> +			<div class="col fourth-promo-img"></div>
Hi this is good every works fine althought these divs  here are suppose to be links that is wrapped within an a tag like I stated in the last review. You could correct that and submit this project. :+1:  goodluck on your next project :+1:

2019-08-07 14:13 UTC, merged